AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Initializer Role template ServiceCatalog

Resources:
  InitializerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ServiceCatalogInitializer
      Path: /servicecatalog/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess